name: Changelog

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: 'write'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout action
        uses: actions/checkout@v3
        repository: jamthehackerscat/changelog-action
        token: ${{ secrets.GIT_TOKEN }}
        path: ../.private-changelog-action
        ref: main

      - name: Changelog
        id: changelog
        uses: ../.private-changelog-action
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: true
          includeInvalidCommits: true
          excludeTypes: ""

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
          reverseOrder: true
          excludeTypes: skip
