name: Changelog

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: 'write'
  pull-requests: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout action
        uses: actions/checkout@v3
        with:
          repository: jamthehackerscat/changelog-action
          token: ${{ secrets.GIT_TOKEN }}
          path: changelog-action
          ref: main

      - name: Changelog
        id: changelog
        uses: ./changelog-action
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: true
          includeInvalidCommits: true
          excludeTypes: ""

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: changelog
          create_branch: true
          commit_message: 'skip: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
          reverseOrder: true
          excludeTypes: skip

      - name: create branch pull request
        run: |
          gh pr create -B main -H changelog --title 'skip: Updated Changelog' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}
